

var x = 8;

console.log("A")
try{
console.log(x/4);
console.log("try...block")
}catch(er){
    console.log("Error")
    console.log("catch...block")
}
console.log("B")